name: cusp
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14
  - certifi=2020.12.5
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.3.1
  - python=3.7.9
  - readline=8.0
  - setuptools=51.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - atari-py==0.2.6
    - attrs==20.3.0
    - cached-property==1.5.2
    - cachetools==4.2.0
    - cffi==1.14.4
    - chardet==4.0.0
    - click==7.0
    - cloudpickle==1.2.2
    - collision==1.2.2
    - cycler==0.10.0
    - cython==0.29.21
    - dataclasses==0.6
    - dm-control==0.0.322773188
    - dm-env==1.3
    - dm-tree==0.1.5
    - dmc2gym==1.0.0
    - fasteners==0.15
    - future==0.18.2
    - glfw==2.0.0
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.34.0
    - gym==0.18.0
    - h5py==3.1.0
    - hydra-core==0.11.3
    - idna==2.10
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - importlib-metadata==3.1.1
    - iniconfig==1.1.1
    - joblib==0.17.0
    - jsonnet==0.17.0
    - kiwisolver==1.3.1
    - kociemba==1.2.1
    - labmaze==1.0.3
    - lxml==4.6.2
    - markdown==3.3.3
    - matplotlib==3.1.2
    - mazebase==0.0.1
    - mock==4.0.2
    - monotonic==1.5
    - mujoco-py==2.0.2.13
    - numpy==1.19.4
    - oauthlib==3.1.0
    - opencv-python==4.5.1.48
    - packaging==20.7
    - pandas==1.2.0
    - pillow==7.2.0
    - pluggy==0.13.1
    - protobuf==3.14.0
    - psutil==5.8.0
    - py==1.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pycuber==0.2.2
    - pyglet==1.5.0
    - pyopengl==3.1.5
    - pyparsing==2.4.7
    - pytest==6.1.2
    - python-dateutil==2.8.1
    - pytz==2020.5
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.5.4
    - six==1.15.0
    - stable-baselines3==0.10.0
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch==1.7.1
    - torchvision==0.8.2
    - tqdm==4.56.2
    - transforms3d==0.3.1
    - trimesh==3.8.18
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - zipp==3.4.0
